### ISSUE TITLE
Story

### ISSUE THREAD

**Issue by Hagimo** [Hagimo/CopyPasta-team#10]
Napady na story?

**Comment by PepeDuke** [comment]
predloha: jako < nekdo>, ja chci <něco> aby <proč>

**Comment by PepeDuke** [comment]
pri to aby nemusime

**Comment by Hagimo** [comment]
Třeba: osoby co posílají příspěvky chtějí dostávat upozornění o tom v jakém stavu je jejich příspěvek.

**Comment by HanaNovakova** [comment]
Majitel - vzhled stánky ´- proto
redaktor- vkládání článků - jen tak

**Comment by HanaNovakova** [comment]
tak odběratelé - zpětná vazba ?

**Comment by PepeDuke** [comment]
nejdrív asi autor a redaktor a atd. zbytek pak muzem dat majiteli

**Comment by HanaNovakova** [comment]
tak ten můj výtvor někdo smažte, prosím

**Comment by PepeDuke** [comment]
ja du do prace a přijedu v patek, tak se na to podivam v patek

**Comment by PepeDuke** [comment]
pridal jsem tam autora, majitele a redaktora. ale nejsem si jitej ke komu přadit ty tasky

**Comment by Hagimo** [comment]
Koukal jsem na to. 
Ještě jedna poznámka. Když ten story bude hotový, tak můžeme dát že je to hotové a 0 hodin(vyčerpáno) , jelikož v seenowdo.com když chceš vidět vše i to co je hotové nesmíte mít zaškrtnuté Hide Completed Stories
