### ISSUE TITLE
Vzhled stárnky

### ISSUE THREAD

**Issue by HanaNovakova** [Hagimo/CopyPasta-team#11]
![vzhled](https://user-images.githubusercontent.com/26274908/32167840-8e2d9336-bd6a-11e7-95f6-53ae5d4b5f53.png)

**Comment by HanaNovakova** [comment]
![bez nazvu](https://user-images.githubusercontent.com/26274908/32168839-63ffa92e-bd6e-11e7-8c59-a3f35d40a880.png)

**Comment by Hagimo** [comment]
![nepojmenovany 2](https://user-images.githubusercontent.com/32642885/32170002-1fe1d104-bd73-11e7-9d54-711b88061eb9.jpg)

**Comment by HanaNovakova** [comment]
![bez nazvu](https://user-images.githubusercontent.com/26274908/32170568-49bcdf62-bd75-11e7-9142-9da95f4501fd.png)

**Comment by Hagimo** [comment]
To je jen návrh, barvy se mohou měnit. A téma tam je jen proto aby jsme věděli co tam má být , tam pak bude sport a atd.

**Comment by HanaNovakova** [comment]
![bez nazvu](https://user-images.githubusercontent.com/26274908/32171759-8935eed2-bd79-11e7-82f3-6403812753fb.png)

**Comment by PepeDuke** [comment]
menu jeno but nahoře nebo podelně nikdy ne boji jako mapř. vspj.cz tam to maji zrovna blbje. dal bych asi vrchní menu.

**Comment by PepeDuke** [comment]
![navrh](https://user-images.githubusercontent.com/32746699/32173893-a09ce718-bd80-11e7-9a27-b4e61bd91678.png)
