### ISSUE TITLE
Seenowdo

### ISSUE THREAD

**Issue by Hagimo** [Hagimo/CopyPasta-team#15]
Už jsem to asi pochopil. Viz příloha.
![untitled 1](https://user-images.githubusercontent.com/32642885/32607702-1cdb5d24-c55a-11e7-8434-9a0fab53a728.jpg)

**Comment by PepeDuke** [comment]
a pak ze to neklesá ten zelenej se sotva pohl a oranzova vyletela do stratosfery

**Comment by Hagimo** [comment]
Takže to funguje v pohodě.

**Comment by HanaNovakova** [comment]
no tak skvělé

**Comment by Hagimo** [comment]
Odebral jsem hodinu u učení Seenowdo :D

**Comment by Hagimo** [comment]
A učení v Gitbuba jsem dal do comlpeted, když tak to navýším.
