### ISSUE TITLE
Porada

### ISSUE THREAD

**Issue by Hagimo** [Hagimo/CopyPasta-team#20]

**Comment by Hagimo** [comment]
Přidal jsem do Seenowdo zobrazování časopisů a přidal tvorba prezentace. Do Completed bych dal vše jako je Komunikace s majitelem, porady atd , jako že se to týkalo prvního sprintu a pro druhý sprint bych to udělal znova, jo ?

**Comment by HanaNovakova** [comment]
ok

**Comment by HanaNovakova** [comment]
Co vše do té prezentace?

**Comment by Hagimo** [comment]
Ok

**Comment by Hagimo** [comment]
Tlačítko Home má mít jakou funkci ? Odkaz na články nebo info o časopisu ?

**Comment by PepeDuke** [comment]
tam by mělí byt actuality

**Comment by Hagimo** [comment]
OK
